<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Contractor;
use Illuminate\Support\Facades\Hash;

class ContractorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // إنشاء مستخدمين ومقاولين مرتبطين بهم
        $contractorData = [
        
    [
        'company_name' => 'شركة الأفق',
        'commercial_registration_number' => 'CR10001',
        'company_email' => 'ofok@example.com',
        'country' => 'سوريا',
        'city' => 'حلب',
        'phone_number' => '0987654321',
        'year_established' => 2012,
        'projects_last_5_years' => 6,
        'quality_certificates' => 2,
        'public_sector_successful_contracts' => 'مشاريع مع التعليم العالي والصحة',
        'website_url' => 'https://ofok.com',
        'linkedin_profile' => 'https://linkedin.com/in/ofok',
        'company_bio' => 'تعمل الشركة في مجال الإنشاءات العامة ومشاريع الطرق.',
        'official_documents' => 'documents/ofok.pdf',
    ],
    [   'company_name' => 'شركة نيوسير',
        'commercial_registration_number' => 'CR342',
        'company_email' => 'neoser@example.com',
        'country' => 'سوريا',
        'city' => 'دمشق',
        'phone_number' => '0987650441',
        'year_established' => 2010,
        'projects_last_5_years' => 8,
        'quality_certificates' => 1,
        'public_sector_successful_contracts' => 'مشاريع مع وزارة الأشغال العامة',
        'website_url' => 'https://neoser.com',
        'linkedin_profile' => 'https://linkedin.com/in/neoser',
        'company_bio' => 'تعمل الشركة في مجال البناء والخدمات الصحية والخدمية.',
        'official_documents' => 'documents/neoser.pdf',
    ],
    [
        'company_name' => 'شركة البنيان',
        'commercial_registration_number' => 'CR876',
        'company_email' => 'albunyan@example.com',
        'country' => 'سوريا',
        'city' => 'اللاذقية',
        'phone_number' => '0943216789',
        'year_established' => 2015,
        'projects_last_5_years' => 5,
        'quality_certificates' => 3,
        'public_sector_successful_contracts' => 'مشاريع مياه وصرف صحي',
        'website_url' => 'https://albunyan.com',
        'linkedin_profile' => 'https://linkedin.com/in/albunyan',
        'company_bio' => 'تقدم خدمات البناء المدنية والهندسية.',
        'official_documents' => 'documents/albunyan.pdf',
    ],
    [
        'company_name' => 'شركة البناء الحديث',
        'commercial_registration_number' => 'CR223',
        'company_email' => 'modernbuild@example.com',
        'country' => 'سوريا',
        'city' => 'دمشق',
        'phone_number' => '0987123456',
        'year_established' => 2008,
        'projects_last_5_years' => 10,
        'quality_certificates' => 2,
        'public_sector_successful_contracts' => 'مشاريع طرق وجسور',
        'website_url' => 'https://modernbuild.com',
        'linkedin_profile' => 'https://linkedin.com/in/modernbuild',
        'company_bio' => 'شركة رائدة في مجال الإنشاءات الحديثة.',
        'official_documents' => 'documents/modernbuild.pdf',
    ],
    [
        'company_name' => 'شركة الشام للمقاولات',
        'commercial_registration_number' => 'CR565',
        'company_email' => 'shamco@example.com',
        'country' => 'سوريا',
        'city' => 'حلب',
        'phone_number' => '0945671234',
        'year_established' => 2011,
        'projects_last_5_years' => 7,
        'quality_certificates' => 1,
        'public_sector_successful_contracts' => 'مشاريع مدارس ومستشفيات',
        'website_url' => 'https://shamco.com',
        'linkedin_profile' => 'https://linkedin.com/in/shamco',
        'company_bio' => 'خبراء في مجال المقاولات العامة والبناء.',
        'official_documents' => 'documents/shamco.pdf',
    ],
    [
        'company_name' => 'شركة القلم للمقاولات',
        'commercial_registration_number' => 'CR778',
        'company_email' => 'alqalam@example.com',
        'country' => 'سوريا',
        'city' => 'حمص',
        'phone_number' => '0954321789',
        'year_established' => 2013,
        'projects_last_5_years' => 6,
        'quality_certificates' => 2,
        'public_sector_successful_contracts' => 'مشاريع البنية التحتية والكهرباء',
        'website_url' => 'https://alqalam.com',
        'linkedin_profile' => 'https://linkedin.com/in/alqalam',
        'company_bio' => 'توفير خدمات البناء والتطوير العمراني.',
        'official_documents' => 'documents/alqalam.pdf',
    ],
    [
        'company_name' => 'شركة الريان',
        'commercial_registration_number' => 'CR334',
        'company_email' => 'alrayan@example.com',
        'country' => 'سوريا',
        'city' => 'دمشق',
        'phone_number' => '0987654322',
        'year_established' => 2016,
        'projects_last_5_years' => 4,
        'quality_certificates' => 1,
        'public_sector_successful_contracts' => 'مشاريع إسكان وتطوير حضري',
        'website_url' => 'https://alrayan.com',
        'linkedin_profile' => 'https://linkedin.com/in/alrayan',
        'company_bio' => 'شركة متخصصة في البناء والتطوير العقاري.',
        'official_documents' => 'documents/alrayan.pdf',
    ],
    [
        'company_name' => 'شركة البناء العادل',
        'commercial_registration_number' => 'CR442',
        'company_email' => 'albenaa@example.com',
        'country' => 'سوريا',
        'city' => 'حلب',
        'phone_number' => '0945678900',
        'year_established' => 2010,
        'projects_last_5_years' => 9,
        'quality_certificates' => 3,
        'public_sector_successful_contracts' => 'مشاريع طاقة ومياه',
        'website_url' => 'https://albenaa.com',
        'linkedin_profile' => 'https://linkedin.com/in/albenaa',
        'company_bio' => 'رائدة في مشاريع الطاقة والمياه.',
        'official_documents' => 'documents/albenaa.pdf',
    ],
    [
        'company_name' => 'شركة الأمل للبناء',
        'commercial_registration_number' => 'CR993',
        'company_email' => 'amalbuild@example.com',
        'country' => 'سوريا',
        'city' => 'دمشق',
        'phone_number' => '0981234567',
        'year_established' => 2014,
        'projects_last_5_years' => 5,
        'quality_certificates' => 2,
        'public_sector_successful_contracts' => 'مشاريع الطرق والصرف الصحي',
        'website_url' => 'https://amalbuild.com',
        'linkedin_profile' => 'https://linkedin.com/in/amalbuild',
        'company_bio' => 'شركة متخصصة في مشاريع البنية التحتية.',
        'official_documents' => 'documents/amalbuild.pdf',
    ],
    [
        'company_name' => 'شركة الصرح',
        'commercial_registration_number' => 'CR555',
        'company_email' => 'alsarh@example.com',
        'country' => 'سوريا',
        'city' => 'اللاذقية',
        'phone_number' => '0948765432',
        'year_established' => 2009,
        'projects_last_5_years' => 10,
        'quality_certificates' => 1,
        'public_sector_successful_contracts' => 'مشاريع مجمعات سكنية',
        'website_url' => 'https://alsarh.com',
        'linkedin_profile' => 'https://linkedin.com/in/alsarh',
        'company_bio' => 'شركة مقاولات متخصصة في السكن.',
        'official_documents' => 'documents/alsarh.pdf',
    ],
    [
        'company_name' => 'شركة البيان',
        'commercial_registration_number' => 'CR667',
        'company_email' => 'albayan@example.com',
        'country' => 'سوريا',
        'city' => 'حماة',
        'phone_number' => '0956789123',
        'year_established' => 2011,
        'projects_last_5_years' => 7,
        'quality_certificates' => 2,
        'public_sector_successful_contracts' => 'مشاريع مدارس ومستشفيات',
        'website_url' => 'https://albayan.com',
        'linkedin_profile' => 'https://linkedin.com/in/albayan',
        'company_bio' => 'شركة مقاولات عامة ومتخصصة.',
        'official_documents' => 'documents/albayan.pdf',
    ],
    [
        'company_name' => 'شركة التقدم',
        'commercial_registration_number' => 'CR889',
        'company_email' => 'altaqaddum@example.com',
        'country' => 'سوريا',
        'city' => 'حمص',
        'phone_number' => '0957891234',
        'year_established' => 2013,
        'projects_last_5_years' => 6,
        'quality_certificates' => 1,
        'public_sector_successful_contracts' => 'مشاريع حكومية مختلفة',
        'website_url' => 'https://altaqaddum.com',
        'linkedin_profile' => 'https://linkedin.com/in/altaqaddum',
        'company_bio' => 'تقدم خدمات مقاولات متعددة.',
        'official_documents' => 'documents/altaqaddum.pdf',
    ],
    [
        'company_name' => 'شركة السواعد',
        'commercial_registration_number' => 'CR777',
        'company_email' => 'alsa3id@example.com',
        'country' => 'سوريا',
        'city' => 'دمشق',
        'phone_number' => '0989876543',
        'year_established' => 2015,
        'projects_last_5_years' => 5,
        'quality_certificates' => 3,
        'public_sector_successful_contracts' => 'مشاريع البنية التحتية',
        'website_url' => 'https://alsa3id.com',
        'linkedin_profile' => 'https://linkedin.com/in/alsa3id',
        'company_bio' => 'شريك موثوق في مشاريع البناء.',
        'official_documents' => 'documents/alsa3id.pdf',
    ],
    [
        'company_name' => 'شركة الريادة',
        'commercial_registration_number' => 'CR888',
        'company_email' => 'alriyada@example.com',
        'country' => 'سوريا',
        'city' => 'حلب',
        'phone_number' => '0943219876',
        'year_established' => 2010,
        'projects_last_5_years' => 8,
        'quality_certificates' => 2,
        'public_sector_successful_contracts' => 'مشاريع الطرق والكهرباء',
        'website_url' => 'https://alriyada.com',
        'linkedin_profile' => 'https://linkedin.com/in/alriyada',
        'company_bio' => 'شركة رائدة في المقاولات.',
        'official_documents' => 'documents/alriyada.pdf',
    ],
    [
        'company_name' => 'شركة المستقبل',
        'commercial_registration_number' => 'CR999',
        'company_email' => 'almustaqbal@example.com',
        'country' => 'سوريا',
        'city' => 'دمشق',
        'phone_number' => '0987650987',
        'year_established' => 2017,
        'projects_last_5_years' => 3,
        'quality_certificates' => 1,
        'public_sector_successful_contracts' => 'مشاريع الإسكان الاجتماعي',
        'website_url' => 'https://almustaqbal.com',
        'linkedin_profile' => 'https://linkedin.com/in/almustaqbal',
        'company_bio' => 'شركة شابة ومتطورة في البناء.',
        'official_documents' => 'documents/almustaqbal.pdf',
    ],
    [
        'company_name' => 'شركة الراية',
        'commercial_registration_number' => 'CR5555',
        'company_email' => 'alraya@example.com',
        'country' => 'سوريا',
        'city' => 'اللاذقية',
        'phone_number' => '0948765000',
        'year_established' => 2012,
        'projects_last_5_years' => 7,
        'quality_certificates' => 2,
        'public_sector_successful_contracts' => 'مشاريع سياحية وعمرانية',
        'website_url' => 'https://alraya.com',
        'linkedin_profile' => 'https://linkedin.com/in/alraya',
        'company_bio' => 'شركة متميزة في مجالات البناء والسياحة.',
        'official_documents' => 'documents/alraya.pdf',
    ]
];



  $usersData = [
            ['name' => 'Eyad Alkhatib', 'email' => 'eyad@example.com', 'password' => '12345678', 'phone' => '0501234567'],
            ['name' => 'Ahmad Saleh', 'email' => 'ahmad@example.com', 'password' => '12345678', 'phone' => '0507654321'],
            ['name' => 'Sara Nasser', 'email' => 'sara@example.com', 'password' => '12345678', 'phone' => '0501122334'],
            ['name' => 'Mohammed Fadi', 'email' => 'mohammed@example.com', 'password' => '12345678', 'phone' => '0509988776'],
            ['name' => 'Lina Youssef', 'email' => 'lina@example.com', 'password' => '12345678', 'phone' => '0502233445'],
            ['name' => 'Khaled Omar', 'email' => 'khaled@example.com', 'password' => '12345678', 'phone' => '0505566778'],
            ['name' => 'Dana Samir', 'email' => 'dana@example.com', 'password' => '12345678', 'phone' => '0503344556'],
            ['name' => 'Omar Khalil', 'email' => 'omar@example.com', 'password' => '12345678', 'phone' => '0506677889'],
            ['name' => 'Maha Jaber', 'email' => 'maha@example.com', 'password' => '12345678', 'phone' => '0507788990'],
            ['name' => 'Yousef Tarek', 'email' => 'yousef@example.com', 'password' => '12345678', 'phone' => '0504455667'],
            ['name' => 'Rana Said', 'email' => 'rana@example.com', 'password' => '12345678', 'phone' => '0505566443'],
            ['name' => 'Samer Habib', 'email' => 'samer@example.com', 'password' => '12345678', 'phone' => '0503322110'],
            ['name' => 'Huda Fares', 'email' => 'huda@example.com', 'password' => '12345678', 'phone' => '0509988771'],
            ['name' => 'Nabil Adel', 'email' => 'nabil@example.com', 'password' => '12345678', 'phone' => '0506677443'],
            ['name' => 'Rami Ziad', 'email' => 'rami@example.com', 'password' => '12345678', 'phone' => '0505544332'],
            ['name' => 'Nada Fadi', 'email' => 'nada@example.com', 'password' => '12345678', 'phone' => '0507766554'],
            ['name' => 'Bassam Khaled', 'email' => 'bassam@example.com', 'password' => '12345678', 'phone' => '0504433221'],
            ['name' => 'Lamia Tarek', 'email' => 'lamia@example.com', 'password' => '12345678', 'phone' => '0508899001'],
            ['name' => 'Adel Sami', 'email' => 'adel@example.com', 'password' => '12345678', 'phone' => '0503344667'],
            ['name' => 'Dina Mahmoud', 'email' => 'dina@example.com', 'password' => '12345678', 'phone' => '0506655443'],
        ];
foreach ($contractorData as $index => $contractorData) {
    $userData = $usersData[$index];
    $user = User::create([
        'name' => $userData['name'],
        'email' => $userData['email'],
        'password' => Hash::make($userData['password']),
        'phone' => $userData['phone'],
    ]);

    $contractorData['user_id'] = $user->id;

    Contractor::create($contractorData);
}

}
}